# Generated by Django 3.1.7 on 2021-03-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_question', models.CharField(max_length=40)),
                ('second_question', models.CharField(max_length=40)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('name2', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
